sudo: false

language: scala

scala:
  - 2.12.2

jdk:
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt -jvm-opts .travis.jvmopts -sbt-version 0.13.15 -scala-version $TRAVIS_SCALA_VERSION ';clean ;test:compile'
  - ./.travis-test.sh coreJVM
  - ./.travis-test.sh examplesJVM
  - ./.travis-test.sh junitJVM
  - ./.travis-test.sh matcherExtraJVM
  - ./.travis-test.sh mockJVM
  - ./.travis-test.sh scalacheckJVM
  - ./.travis-test.sh scalazJVM
  - ./.travis-test.sh shapelessJVM

  - ./.travis-test.sh coreJS
  - ./.travis-test.sh examplesJS

  - ./.travis-test.sh gwt
  - ./.travis-test.sh html
  - ./.travis-test.sh markdown
  - ./.travis-test.sh tests

  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f43e8d682579a80ef5f
    on_success: always
    on_failure: always
    on_start: false
