# needed to get oraclejdk8
dist: trusty

language: scala

scala:
  - 2.12.8
  - 2.11.12
  - 2.13.0

jdk:
  - oraclejdk8
  - openjdk11

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:

  - ./.travis-test.sh coreJVM
  - ./.travis-test.sh tests

  - ./.travis-test.sh catsJVM
  - ./.travis-test.sh examplesJVM
  - ./.travis-test.sh junitJVM
  - ./.travis-test.sh matcherExtraJVM
  - ./.travis-test.sh mockJVM
  - ./.travis-test.sh scalacheckJVM
  - ./.travis-test.sh scalazJVM
  - ./.travis-test.sh shapelessJVM
  - ./.travis-test.sh gwtJVM
  - ./.travis-test.sh markdownJVM
  - ./.travis-test.sh formJVM

  - ./.travis-test.sh html

  - ./.travis-test.sh coreJS
  - ./.travis-test.sh catsJS
  - ./.travis-test.sh examplesJS

  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f43e8d682579a80ef5f
    on_success: always
    on_failure: always
    on_start:   never

matrix:
  include:
  - scala: 2.11.12
    jdk: openjdk8
    before_script:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -
    sudo: required
    script:
      - ./.travis-test.sh coreNative
      - ./.travis-test.sh examplesNative
